sheet.csv.url=https://docs.google.com/spreadsheets/d/e/2PACX-1vRq5333uDknaIEAfknHnBUzzWIQTscx7FZGJG7jaMRobHYayJt5M-CqB4scd9kMCHq8IOnuyMW8RDUd/pub?output=csv
server.port=8080

openai.api.key=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
