sheet.csv.url=https://docs.google.com/spreadsheets/d/e/2PACX-1vRq5333uDknaIEAfknHnBUzzWIQTscx7FZGJG7jaMRobHYayJt5M-CqB4scd9kMCHq8IOnuyMW8RDUd/pub?output=csv
server.port=8080

openai.api.key=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
